version: '3.7'

services:
  fastapi-starter-template:
    container_name: fastapi-starter-template
    image: fastapi-starter-template
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - ./:/src
    ports:
      - "16000:8000"
      - "5678:5678"
    
    depends_on:
      app_db:
        condition: service_healthy

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 36379:6379

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"